plugins: ['@trivago/prettier-plugin-sort-imports']
printWidth: 80
tabWidth: 2
singleQuote: true
semi: false
importOrder: [
    '^@/(.*)$',
  ]
importOrderSeparation: true
importOrderSortSpecifiers: true
arrowParens: 'avoid'
